### ISSUE TITLE
Password not recognized after loadPBAimage and power cycle on Crucial MX200

### ISSUE THREAD

**Issue by luismcv** [r0m30/msed#16] opened 2015-03-21 20:18 UTC
Hi.

I'm not sure if it's a bug in the firmware of the Crucial MX200 or in MSED. After loading the PBA image and doing a power cycle the password (set up with --initialsetup and that I've been using for all the other steps) stops working, neither the PBA nor msed are able to unlock the drive and the only solution I've found is doing a complete reset with the PSID. 

It only happens with loadPBAimage. Other commands like --setMBREnable and --enableLockingRange 0 work fine, even after a power cycle. So you can lock the drive, but you can't use the PBA feature, you need to use another drive or usb flash to boot.

Tested several times.

**Comment by luismcv** [comment] 2015-03-21 20:22
If forgot to mention that loadPBAimage works fine on a Samsung 840 EVO, using the same binaries (msed and the pba image).

**Comment by r0m30** [comment] 2015-03-22 12:58
Honestly, my first reaction is firmware bug, but lets do some validation.
Can you please try this to see if we can isolate the issue:

First lets see that msed is passing the same hash before and after the loadPBAimage (to shorten the time it takes to load the PBA you might want to use a small text file instead of the real PBA).

msed --initialsetup password \\.\PhysiclaDrive?
msed --query \\.\PhysicalDrive?               (check the serial number)
msed -vvvv --setMBRDone on \\.\PhysicalDrive? >before.trace.txt 2>&1
msed --loadPBAimage password <pbafile>\\.\PhysiclaDrive?
msed --query \\.\PhysicalDrive?               (check the serial number)
msed -vvvv --setMBRDone on \\.\PhysicalDrive? >after.trace.txt 2>&1

We can then look at the password hash passed before and after the load to see if it is the same.

**Comment by luismcv** [comment] 2015-03-22 13:21
Hi. I'm afraid that I can't do any more tests, after finishing installing everything last night I don't want to start all over again :/

Anyway, I think that what you suggest wouldn't help:

   - If you did all the steps that you mentioned they will work just fine, it doesn't even matter in which order, as far as you don't power cycle. It's after a power cycle that the password isn't recognised anymore, neither from the PBA nor msed itself.

   - If you do all the steps except "--loadPBAimage' the password still works after a power cycle.

   - As soon as you load the PBA image and power cycle, you're locked out of the drive.

So the bug, whether in the firmware or in msed, seems to be that the password is corrupted after loading the PBA and not that the password hash sent to the drive changes.

**Comment by luismcv** [comment] 2015-03-22 13:22
Hmm, unless... I'm thinking... do you use any information from the drive to generate the hash? Maybe that's what changes after uploading the PBA and power cycling.

**Comment by r0m30** [comment] 2015-03-22 13:34
I understand.

Yes, I use the drive serial number as the salt for the PBKDF2<SHA1> function used to hash the password.  So it would require a query before and after the power cycle to see if that has changed.

Other commands work after the loadPBAimage until the power cycle?  That seems very strange.

**Comment by luismcv** [comment] 2015-03-22 13:56
Yes, every other command worked fine before a power cycle, even if you just did a reboot.

Yes, strange. But it wasn't the only weird thing I found yesterday. A bit unrelated, but I was doing a PSID secure reset to a Samsung 840 EVO, and while the Crucial needed the whole PSID (as it should), the 840 EVO was happy with just the start of the string. With even only the very first character it was happy to reset itself. With any changes or extra characters failed. It'd seem the firmware just does a sort of hardwarepsid.startsWith(enteredpsid) check.

**Comment by r0m30** [comment] 2015-03-22 14:40
Are you using 0.22beta?  There was a bug in some versions of msed where the return code was corrupted if the session startup failed.  Did you just get the reverttper complete message or did you get a NOT_AUTHORIZED message and then the reverttper complete message when you were reverting the 840 EVO?

**Comment by luismcv** [comment] 2015-03-22 15:03
Yes, 0.22beta. I didn't get any errors (as far as the password I entered matched the start of the PSID) and the 840 EVO was resetting itself just fine. I checked it by doing a md5sum of a few bytes taken from different LBA positions. Each time I did a reset the md5 changed, so the drive was definitely generating a new AES key.

By the way, I was using the --yesIreallywantto.... option, not reverttper, because the latter gave me NOT_AUTHORIZED errors on the MX200 despite the password being right (I didn't try with the EVO). Are they any different?

**Comment by r0m30** [comment] 2015-03-22 15:27
Yes, reverttper requires the sid password not the PSID,  It is useful when you want to disable OPAL mode (revertnoerase and then reverttper).

**Comment by riklaunim** [comment] 2015-05-10 22:25
I also have Crucial MX200 and I also have problem with it. Following http://vxlabs.com/2015/02/11/use-the-hardware-based-full-disk-encryption-your-tcg-opal-ssd-with-msed/ I run (Kubuntu 15.04):
*  --initialsetup
* --loadPBAimage
* --setMBREnable
* --enableLockingRange

and after power off/on I go the unlock prompt. However it would not unlock when I entered the password.  I would just print "is opal failed" somewhere to right side of the screen and asking for password once again. When I booted Kubuntu LiveDVD I was able to change the passwords (so the old one was good), but that didn't help either. Then I just used --revertnoerase which unlocked the SSD (although empty).

**Comment by r0m30** [comment] 2015-05-11 13:30
Are you using a non-US keyboard?  If so try using a passphrase that is only lowercase letters, or setting the password on the liveCD with the US keyboard selected.

**Comment by riklaunim** [comment] 2015-05-11 13:33
the keyboard is for UK and the system keyboard layout is Polish. at first I used alphanumeric plus @ then I changed only to alphanumeric (lowercase in both cases). And it's QWERTY.

**Comment by r0m30** [comment] 2015-05-11 16:12
Can you try and do the setup with the Rescue system and see what happens, that has the US keymap so it should match the PBA.

**Comment by riklaunim** [comment] 2015-05-11 23:49
I tried running commands on it but after "revertnoerase" I get things like:
```
- 01:45:36.900 ERR : method status code INVALID_PARAMETER
- 01:45:36.900 ERR : Session start failed
- 01:45:36.925 ERR : One or more header fields have 0 length
- 01:45:36.925 ERR : EndSession Failed
```
For pba image loading or password change. initialsetup also can't be done - NOT_AUTHORIZED

**Comment by r0m30** [comment] 2015-05-12 06:12
Did you issue the reverttper after the revert noersase?  (http://www.r0m30.com/msed/documentation/managing/removeopal) the invalid paramater is usually means you didn't.  
That would also explain the not authorized messages.

If that doesn't work then it's probably PSID revert time.

**Comment by riklaunim** [comment] 2015-05-13 22:34
I've reverted, tried again with Kubuntu LieDVD with English and standard keymap + very basic password with no luck. USB flash drive doesn't want to boot after burning the rescue image with dd + sync (but I'll check another one too).

**Comment by r0m30** [comment] 2015-05-14 10:43
Can you do a query on the drive before and after.  It's almost like the serial number is changing.?.?

**Comment by riklaunim** [comment] 2015-05-14 22:19
Start:
```
- 23:53:46.405 DBG : Log level set to DBG 
- 23:53:46.405 DBG : msed version : 0.23beta
- 23:53:46.432 DBG : Performing diskquery() on /dev/sda

/dev/sda ATA Crucial_CT250MX200SSD1                   MU01             15030E6BFD29
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = N, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = Y, Alignment Granularity = 8 (4096), Logical Block size = 512, Lowest Aligned LBA = 0
SingleUser function (0x0201)
    ALL = N, ANY = N, Policy = Y, Locking Objects = 16
DataStore function (0x0202)
    Max Tables = 16, Max Size Tables = 94371840, Table size alignment = 1
OPAL 2.0 function (0x0203)
    Base comID = 0x1000, Initial PIN = 0x0, Reverted PIN = 0x0, comIDs = 1
    Locking Admins = 4, Locking Users = 16, Range Crossing = N

TPer Properties: 
  MaxComPacketSize = 131072  MaxResponseComPacketSize = 131072
  MaxPacketSize = 129792  MaxIndTokenSize = 126976  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxSessions = 1
  MaxAuthentications = 21  MaxTransactionLimit = 1  DefSessionTimeout = 240000

Host Properties: 
  MaxComPacketSize = 2048  MaxResponseComPacketSize = 2048
  MaxPacketSize = 2028  MaxIndTokenSize = 1992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1
```

After setting up everything:
```
- 23:55:52.748 DBG : Log level set to DBG 
- 23:55:52.749 DBG : msed version : 0.23beta
- 23:55:52.776 DBG : Performing diskquery() on /dev/sda

/dev/sda ATA Crucial_CT250MX200SSD1                   MU01             15030E6BFD29
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = Y, LockingSupported = Y, MBRDone = Y, MBREnabled = Y, MediaEncrypt = Y
Geometry function (0x0003)
    Align = Y, Alignment Granularity = 8 (4096), Logical Block size = 512, Lowest Aligned LBA = 0
SingleUser function (0x0201)
    ALL = N, ANY = N, Policy = Y, Locking Objects = 16
DataStore function (0x0202)
    Max Tables = 16, Max Size Tables = 94371840, Table size alignment = 1
OPAL 2.0 function (0x0203)
    Base comID = 0x1000, Initial PIN = 0x0, Reverted PIN = 0x0, comIDs = 1
    Locking Admins = 4, Locking Users = 16, Range Crossing = N

TPer Properties: 
  MaxComPacketSize = 131072  MaxResponseComPacketSize = 131072
  MaxPacketSize = 129792  MaxIndTokenSize = 126976  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxSessions = 1
  MaxAuthentications = 21  MaxTransactionLimit = 1  DefSessionTimeout = 240000

Host Properties: 
  MaxComPacketSize = 2048  MaxResponseComPacketSize = 2048
  MaxPacketSize = 2028  MaxIndTokenSize = 1992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1
```

Before reverting from LiveDVD:

```
- 22:15:18.813 DBG : Log level set to DBG                                                                                                                                                       
- 22:15:18.813 DBG : msed version : 0.23beta                                                                                                                                                    
- 22:15:18.840 DBG : Performing diskquery() on /dev/sda                                                                                                                                         
                                                                                                                                                                                                
/dev/sda ATA Crucial_CT250MX200SSD1                   MU01             15030E6BFD29                                                                                                             
TPer function (0x0001)                                                                                                                                                                          
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y                                                                                                  
Locking function (0x0002)                                                                                                                                                                       
    Locked = Y, LockingEnabled = Y, LockingSupported = Y, MBRDone = N, MBREnabled = Y, MediaEncrypt = Y                                                                                         
Geometry function (0x0003)                                                                                                                                                                      
    Align = Y, Alignment Granularity = 8 (4096), Logical Block size = 512, Lowest Aligned LBA = 0                                                                                               
SingleUser function (0x0201)                                                                                                                                                                    
    ALL = N, ANY = N, Policy = Y, Locking Objects = 16                                                                                                                                          
DataStore function (0x0202)                                                                                                                                                                     
    Max Tables = 16, Max Size Tables = 94371840, Table size alignment = 1                                                                                                                       
OPAL 2.0 function (0x0203)                                                                                                                                                                      
    Base comID = 0x1000, Initial PIN = 0x0, Reverted PIN = 0x0, comIDs = 1
    Locking Admins = 4, Locking Users = 16, Range Crossing = N

TPer Properties: 
  MaxComPacketSize = 131072  MaxResponseComPacketSize = 131072
  MaxPacketSize = 129792  MaxIndTokenSize = 126976  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxSessions = 1
  MaxAuthentications = 21  MaxTransactionLimit = 1  DefSessionTimeout = 240000

Host Properties: 
  MaxComPacketSize = 2048  MaxResponseComPacketSize = 2048
  MaxPacketSize = 2028  MaxIndTokenSize = 1992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1
```

**Comment by riklaunim** [comment] 2015-05-17 18:36
Tried with centos liveCD with the same effect. Maybe the laptop itself may cause some specific issues?

**Comment by r0m30** [comment] 2015-05-18 00:42
sorry, I missed the notification of your post with the queries.  I was hoping the serial number was altered in some way but it doesn't look like it.

I'm not sure if it's an issue with the laptop or the drive.  I don't have access to a MX200 to do any real testing and none of the remote debugging has given me the slightest clue about what is wrong.

**Comment by luismcv** [comment] 2015-05-18 05:45
Considering that (as above) I also had the same issue with the same drive in a completely different machine (ga-z97x-ud3h motherboard) where an 840 EVO worked fine, I'd say the issue is related to the MX200.

Unfortunately, both my drives are being used in RAID and I don't have neither the additional disk space nor the time to mirror one somewhere else, run some tests and restore it again.

But if riklaunim is still willing to do some tests: r0m30, is it possible to dump the actual hash that it's being sent to the drive before and after uploading the PBA image and doing a power cycle? Probably with -vvvv?

**Comment by r0m30** [comment] 2015-05-18 17:37
Yes, the command buffer right after the "entering MsedHash*" would be the
one with the  hash in it (start session).  I may be getting confused but I
thought riklaunim could still issue commands after the load, it was just
the PBA that was failing????

----------
Mike

**Comment by luismcv** [comment] 2015-05-18 17:55
Oh, I've re-read the thread and realised that I had missed the part where he said he was able to change the password. Then it's not exactly the same case, as I was completely locked out of the drive after a power cycle (at least from both the PBA and your rescue boot image) and all I could do was PSID clear.

**Comment by riklaunim** [comment] 2015-05-18 18:11
Yes, I can use the password to remove the lock with --revertnoerase and --reverttper

**Comment by riklaunim** [comment] 2015-05-18 18:12
I also posted on Crucial forum - http://forum.crucial.com/t5/Crucial-SSDs/MX200-encryption-problem-with-msed-on-Linux/td-p/168231 maybe we will get some help from the vendor too ;)

**Comment by luismcv** [comment] 2015-05-18 18:22
Is there a parameter equivalent to what the PBA does to unlock a drive? Does it work from the kubuntu/centos live cds too?

**Comment by riklaunim** [comment] 2015-05-18 18:23
Didn't saw anything like that.

**Comment by orsc** [comment] 2015-06-23 10:10
I can't confirm the all issues presented here.
Trying to fiddle with my encrypted MX200 with all the different tools gave those results:
I tried version 0.23beta.
msed: everything works as expected, locking / unlocking is fine
biospba: can't unlock the device
LINUXPBA: works as expected with the restriction that it cant be written into the shadow MBR because it seems to be to big. See [Issue #23](https://github.com/r0m30/msed/issues/23).
So right now I'm using the LINUXPBA on an usb-stick to unlock my root drive.
I guess there is a subtle difference between the syslinux approach and the linux image which breaks the biospba.

**Comment by r0m30** [comment] 2015-06-23 22:12
Thanks for investigating this, I don't have a MX200 to test with so this has been frustrating. 
I'll look into adding a restart for the loadPBAimage command to see if that will fix the issue of not being able to load the LINUXPBA on crucial drives ( issue #23), That seems to be consistent throughout the Crucial line including my M500.  Then you won't have to use a USB device for the PBA.

**Comment by orsc** [comment] 2015-07-03 14:51
Here is the output of biospba with TRCE enabled. 
I got the text using an OCR programm. I checked and corrected the output so hopefully there are no mistakes in there.

```
SYSLINUX 6.03 EDD 0.23beta Copyright (C) 1994-2014 H. Peter Anvin et al
Msed PBA for BIOS machines

Enter Pass Phrase to unlock OPAL SSC drives>*****************
DID 96001022 SDID 96001022 CLASS 06000000
DID 96031022 SDID 00000000 CLASS 06040000
DID 96091022 SDID 00000000 CLASS 06040000
DID 43911002 SDID b0021458 CLASS 01060100
Found SATA controller in AHCI mode on the PCI buss @ 80008800
vendor/product 43911002, class 01060100, misc@+0c 00002010
PCI ABAR Registers:
 fe02f000

Found device Identify Crucial_CT250MX200SSD1              MU01
15060EB4AD24
 Crucial_CT250MX200SSD1                  DO response:
0000 000000a0 00000001 00000000 00000000 00000000 00000000 00000000 00000000
0020 00000000 00000000 00000000 00000000 0001100c 11000000 00000000 00000000
0040 0002100c 1f000000 00000000 00000000 0003101c 01000000 00000000 00000200
0060 00000000 00000000 00000000 00000000 0201100c 00000010 04000000 00000000
0080 0202100c 00000010 05a00000 00000001 02031010 10000001 00000400 10000000
00a0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00c0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00e0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
0100 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
0120 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
0140 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
0160 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
0180 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
01a0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
01c0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
01e0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
disk_info:
0000 00007782 ef080000 00000000 00000200 00000000 00000000 00000000 00000410
0020 00000010 000000a0 05010000 00000000 00001001 00000004 00100000 01202020
0040 20202020 20313530 36304542 34414432 34004d55 30312020 20200043 72756369
0060 616c5f43 54323530 4d583230 30535344 31202020 20202020 20202020 20202020
0080 20202000
 is OPAL command:
0000 00000000 10000000 00000000 00000000 0000007c 00000000 00000000 00000000
0020 00000000 00000000 00000064 00000000 00000000 00000058 f8a80000 00000000
0040 00ffa800 00000000 00ff02f0 8169a800 00020500 00000201 f200d020 7a2e543f
0060 14b2b99a a10a262a 93751785 10ed4e55 fb52db0d 5cd3b5fb 4ab522a9 f3f203a8
0080 00000009 00010001 f3f1f9f0 000000f1 00000000 00000000 00000000 00000000
00a0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00c0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00e0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
response:
0000 00000000 10000000 00000000 00000000 00000044 00000000 00000000 00000000
0020 00000000 00000000 0000002c 00000000 00000000 00000020 f8a80000 00000000
0040 00ffa800 00000000 00ff03f0 81698210 00f1f9f0 000000f1 00000000 00000000
0060 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
0080 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00a0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00c0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00e0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
command:
0000 00000000 10000000 00000000 00000000 0000004c 10000000 00000069 00000000
0020 00000000 00000000 00000034 00000000 00000000 00000028 f8a80000 08020000
0040 0001a800 00000600 000017f0 f201f0f2 0700f3f2 0800f3f1 f3f1f9f0 000000f1
0060 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
0080 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00a0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00c0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00e0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
response:
0000 00000000 10000000 00000000 00000000 00000000 00000000 00000000 00000000
0020 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
0040 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
0060 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
0080 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00a0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00c0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00e0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
invalid unlock response (1)
```

**Comment by r0m30** [comment] 2015-07-05 07:03
Strange, the response is empty except for byte four.  This looks similar to the the response I'm seeing for #26.  I don't know why the firmware would respond like this but these issues are happening on crucial drives only so far.

**Comment by r0m30** [comment] 2015-07-20 18:49
@orsc 

You might want to look at https://github.com/cranderson/buildroot-linuxpba  

I'll try and get this built myself soon but it is hard in the summer to carve out the time I need to do all the testing required for a new release.

**Comment by orsc** [comment] 2015-09-06 21:59
@r0m30 thanks for the hint.
I finally found some time to look into this issue more closely.
As mentioned before bisopba produces an error while msed works fine.

So here is a dump of the unlock command sent by biospba / msed:
```text
unlock biospba:
0000 00000000 10000000 00000000 00000000 0000004c 10000000 00000069 00000000
0020 00000000 00000000 00000034 00000000 00000000 00000028 f8a80000 08020000
0040 0001a800 00000600 000017f0 f201f0f2 0700f3f2 0800f3f1 f3f1f9f0 000000f1

unlock msed:
0000 00000000 10000000 00000000 00000000 0000004c 00001000 00000069 00000000
0020 00000000 00000000 00000034 00000000 00000000 00000028 f8a80000 08020000
0040 0001a800 00000600 000017f0 f201f0f2 0700f3f2 0800f3f1 f3f1f9f0 000000f1
```
The TSN differs!
With the right TSN hardcoded I can unlock my disk using the biospba image.

**Comment by r0m30** [comment] 2015-09-07 16:16
Thanks...

That means I'm not parsing the startsession response properly.  Do you have the startsession response in your trace?  It would help with the code analysis.

**Comment by orsc** [comment] 2015-09-07 21:07
Doesn't https://github.com/r0m30/msed/issues/16#issuecomment-118367468 already cover that?
Or do you mean a trace of msed?
I'll provide whatever you need :)

**Comment by r0m30** [comment] 2015-09-07 21:57
Yes it does, sorry.
I think this may be an endian error :-(

**Comment by brianjmurrell** [comment] 2015-09-09 17:45
So, I also seem to be having this "is OPAL Failed" when I try to use biospba on an INTEL SSDSC2BF240A5.  The last time (before my last PSID reset) I was able to use the msed tool with my password just fine.

Will do some more debugging here and report.  While I am doing that, is there anything in particular I can do to help in this issue?

I am using 0.23beta from the Fedora 22 updates repo FWIW, along with http://www.r0m30.com/msed/files/biospba-0.23beta.img.gz

**Comment by r0m30** [comment] 2015-09-09 20:28
I think we have the problem isolated to the TSN handling.  it looks like an endian problem.  Currently I'm working on getting the new Drive Trust Alliance repo (@Drive-Trust-Alliance)  set up and adding a UEFI PBA (Linux based as first).  Then I will be looking at squashing the known bugs.  

This one will probably be the first one.... I just upgraded my system disk to a CX200 and it isn't working with the biosPBA either :-(

**Comment by r0m30** [comment] 2015-09-15 06:15
There is a test fix for this in the files section at www.r0m30.com/msed/files.
It is biospba_test.img int the specialtesting folder.

It works on my MX200

**Comment by bartech9** [comment] 2015-09-22 08:44
Can anyone please confirm it's working? That's the only thing holding me from buying this drive.

**Comment by r0m30** [comment] 2015-09-24 02:04
I've posted a testfix file for loading large PBAs on Crucial driveson r0m30.com. It's issue23.zip in the special testing section on the files page. This should help if you are having problems with the biosPBA not working on you system.

**Comment by bartech9** [comment] 2015-09-24 09:14
Thank you. Should I use it with the biospba_test.img or the regular one?

**Comment by r0m30** [comment] 2015-09-24 11:12
The Linux based one.

________
Mike

**Comment by bartech9** [comment] 2015-09-24 12:13
I thought all of them are linux based.

**Comment by r0m30** [comment] 2015-09-24 17:29
No the biospba one is based on the syslinux bootloader.  The LINUXPBA ones are based on Linux.

**Comment by bartech9** [comment] 2015-09-25 12:00
I confirm that the biospba_test is working flawlessly with the MX200. Although there was a problem with msed on initialsetup. I didn't let me use my password I usually use to encrypt things. I guess that's because of the special chars I use.

**Comment by brianjmurrell** [comment] 2015-10-06 14:56
I can also confirm that {{biospba_test.img}} is also working for me.  So much quicker than a Linux based bootloader.

**Comment by fab128** [comment] 2015-10-06 15:50
biospba_test.img is not working for me. LinuxPBA does

**Comment by r0m30** [comment] 2015-10-06 18:39
Which PBA to use is largely dependent on the hardware configuration of the machine.  boisPBA has a very lean SATA driver which I wrote to work with SYSLINUX.  If that SATA driver fails then the unlock fails.  I've seen this a lot on laptops, usually they have some type of power management to eek the most out of the batteries and I haven't been able to do any real testing to see if I can add that to the biosPBA.  That means you will need to use the LinuxPBA which relies on the much more robust SATA drivers in the Linux Kernel.  

There is also the issue of effort, I think most of the effort going forward will be focused on UEFI as that is going to be what is in use on most systems since it is required for M$ hardware compatibility certification..  

Now that Skylake is starting to hit the shelves in volume I plan on upgrading to a z170/Skylake system, and that will become the primary test environment going forward, so any bios testing will actually be in CSM/Legacy mode of UEFI.

**Comment by r0m30** [comment] 2015-10-06 18:43
@bartech9 

That is probably because of the way your password hashes.  There is restriction on what characters can be used it the passphrase and usually the hashing gets around this but every once in a while Murphy get his digs in.  (is that strictly an American reference?)

**Comment by r0m30** [comment] 2015-10-06 18:48
@brianjmurrell   Yes the biospba is a lot faster.  During development I started with a Linux PBA, hated it so much that I abandoned it and developed the SYSLINUX based one.  Alas there are a lot of configurations that biospba is unable to support so the Linux PBA is alive again.

**Comment by r0m30** [comment] 2015-10-15 23:33
This issue should be fixed in the Drive-Trust-Alliance/sedutil repo.  All future development will be based on that repo.

**Closed by r0m30** 2015-10-15 23:33 UTC
Labels: bug

**Comment by boldandbusted** [comment] 2015-10-23 00:54
FWIW, the file at http://www.r0m30.com/msed/files/biospba_test.img?attredirects=0&d=1 is what I ultimately had to use on my Crucial MX200 drive. Neither of the .23 options worked, nor did http://www.r0m30.com/msed/files/BIOS64_PBA.img?attredirects=0&d=1 .

Thanks. If I can help, I'll be happy to.
